### ISSUE TITLE
Sharing the image does not seem to work

### ISSUE THREAD

**Issue by utack** [devmil/muzei-bingimageoftheday#7]
Hi,  
for some reason v1.6 does not seem to share the image any more.
I tried this
https://github.com/devmil/muzei-bingimageoftheday/commit/a572afadc299c6b7ebfe8770d315d342991a1f26#r32364880
But it was not the root cause of the problem.
Maybe you have another idea.
Thank you!

**Comment by devmil** [comment]
Hi. What do you mean by "does not seem to work"?
Because of the new Muzei API it is no longer possible to share the image directly because the AddOn doesn't have access to the image itself any more.
If you use Muzei 3+ and 1.6+ of this AddOn then not the ArtSource but the ArtProvider is used:
https://github.com/devmil/muzei-bingimageoftheday/blob/master/app/src/main/java/de/devmil/muzei/bingimageoftheday/BingImageOfTheDayArtProvider.kt

**Comment by utack** [comment]
Oh okay, I understand
That is unfortunate, but also unfixable then!
